NDefines.NMilitary.MERCENARY_COMPANY_ARMY_TRADITION = 80
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 200
NDefines.NMilitary.MERCENARY_COMPANY_MIN_REGIMENTS = 6
NDefines.NMilitary.MERCENARY_COMPANY_STARTING_MORALE = 2.5
NDefines.NMilitary.MERCENARY_COMPANY_MANPOWER_PER_REGIMENT = 5
NDefines.NEconomy.LAND_TECH_MERC_MAINTENANCE_IMPACT = 0.02
NDefines.NMilitary.MERCENARY_COMPANY_HIRING_COST_MONTHS = 24
